PREFIX rdcMeta: <http://rdf.biosemantics.org/ontologies/rd-connect/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dummy: <http://rdf.biosemantics.org/ontologies/dummy/>

SELECT DISTINCT ?value { 
    {    
    ?donorURI dummy:hasDisease ?diseaseURI;
             rdfs:seeAlso ?registryDatasetURI;
             rdcMeta:59e1324d_567b_42e1_bc88_203004e660da ?karyotypeInsURI.
    ?karyotypeInsURI a ?karyotypeURI;
                      rdcMeta:7e3fe231_01b9_46b9_8770_f5a5c598d04f ?value.
  }
}