PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?url (STR(?value) AS ?value) { 

    VALUES ?url {obo:SP_0000011 obo:SP_0000003 obo:SP_0000009 obo:SP_0000086
                    obo:SP_0000088 obo:SP_0000165 obo:SP_0000126}

    {
        ?url rdfs:label ?value.
    }
}