PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dummy: <http://rdf.biosemantics.org/ontologies/dummy/>
PREFIX rdcMeta: <http://rdf.biosemantics.org/ontologies/rd-connect/>
PREFIX iao: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (COUNT( DISTINCT ?sampleURI) as ?numberOfSamples)  ?diseaseURI ?disease ?biobank ?biobankURI ?registry ?registryURI  {
  
 VALUES(?diseaseInput) {(<#disease#>)}   
  {
    ?diseaseURI  rdfs:subClassOf* ?diseaseInput.
  }
  {    
    ?donorURI dummy:hasDisease ?diseaseURI; 
              rdfs:seeAlso ?registryDatasetURI.
  }   
  {    
    ?sampleURI rdcMeta:e297332a_00a9_4ed0_b661_00dbd35aff95 ?donorURI;
               rdfs:seeAlso ?biobankDatasetURI. 
  }    
  {    
    ?biobankDatasetURI dct:title ?biobank;
                      rdfs:seeAlso ?biobankURI.
    ?registryDatasetURI dct:title ?registry;
                      rdfs:seeAlso ?registryURI.  
    ?diseaseURI rdfs:label ?disease.  
  }
}  group by ?diseaseURI ?disease ?biobank ?biobankURI ?registry ?registryURI