PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dummy: <http://rdf.biosemantics.org/ontologies/dummy/>
PREFIX rdcMeta: <http://rdf.biosemantics.org/ontologies/rd-connect/>
PREFIX iao: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?sample ?sampleURI ?sampleType ?sampleTypeURI ?biobank ?biobankURI ?disease ?diseaseURI ?karyotype ?karyotypeURI ?breakpoint ?registry ?registryURI {
  
 VALUES(?diseaseURI ?karyotypeURI ?breakpoint) {(<#disease#> <#karyotype#> "#breakpoint#")}   
  {    
    ?donorURI dummy:hasDisease ?diseaseURI;
             rdfs:seeAlso ?registryDatasetURI;
             rdcMeta:59e1324d_567b_42e1_bc88_203004e660da ?karyotypeInsURI.
    ?karyotypeInsURI a ?karyotypeURI;
                      rdcMeta:7e3fe231_01b9_46b9_8770_f5a5c598d04f ?breakpoint.
  }   
  VALUES ?sampleTypeURI {<#sampleType#>}
  {    
    ?sampleURI a  ?sampleTypeURI;   
               rdcMeta:e297332a_00a9_4ed0_b661_00dbd35aff95 ?donorURI;  
               rdfs:seeAlso ?biobankDatasetURI. 
    
    ?sampleIdURI a rdcMeta:21f6df30_1f72_45fb_bfc1_2b3d1af1410a ;
                    dct:identifier ?sample;	
                    iao:IAO_0000219 ?sampleURI.
  }    
  {    
    ?registryDatasetURI dct:title ?registry;
                      rdfs:seeAlso ?registryURI.
    ?biobankDatasetURI dct:title ?biobank;
                      rdfs:seeAlso ?biobankURI.
    ?sampleTypeURI rdfs:label ?sampleType.    
    ?diseaseURI rdfs:label ?disease.  
    ?karyotypeURI rdfs:label ?karyotype.
  }
}